// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// CLI/migration commands need a direct (non-pooled) connection — Prisma Migrate
// doesn't support running through Supabase's PgBouncer-based pooler.
// The running app uses DATABASE_URL (pooled) via the driver adapter in src/lib/prisma.ts instead.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
